
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class Sin1Test extends E2eTestBase {

  public Sin1Test() {
    coreCodeTemplate = "a = 0\ninc = TWO_PI/25\n\nfor (i in seq(0, 100, 4)) {\n    line(i, 50, i, 50 + sin(a) * 40)\n    a = a + inc\n}\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/sin_.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
